"""
build_release.py — Build the CCJ-Translation release zip
=========================================================
Usage:
    py build_release.py

Produces CCJ-Translation.zip containing:
  - All translation .txt files from BepInEx/Translation/en/Text/
  - Only textures listed in translated_textures.txt
  - BepInEx core, plugins, and config (with EnableTextureDumping=False)
"""

import os
import re
import json
import zipfile

BASE        = os.path.dirname(os.path.abspath(__file__))
MANIFEST    = os.path.join(BASE, 'translated_textures.json')
TEXT_DIR    = os.path.join(BASE, 'BepInEx', 'Translation', 'en', 'Text')
CONFIG_FILE = os.path.join(BASE, 'BepInEx', 'config', 'AutoTranslatorConfig.ini')
OUT_ZIP     = os.path.join(BASE, 'CCJ-Translation.zip')

# Folders under BepInEx/ to include wholesale (binaries, config)
BEPINEX_INCLUDE = ['core', 'plugins', 'config', 'patchers']

# Root-level files to include in the zip
ROOT_FILES = ['doorstop.dll', 'doorstop_config.ini']

# Text files to skip (runtime output / backups)
TEXT_SKIP = {'_AutoGeneratedTranslations.txt'}


def load_manifest():
    if not os.path.isfile(MANIFEST):
        print('WARNING: translated_textures.json not found — no textures will be included.')
        return []
    with open(MANIFEST, 'r', encoding='utf-8') as f:
        return json.load(f)


def patch_config(ini_text):
    """Ensure EnableTextureDumping=False in the config."""
    return re.sub(
        r'(?m)^EnableTextureDumping=.*$',
        'EnableTextureDumping=False',
        ini_text,
    )


def build():
    texture_paths = load_manifest()
    print(f'Manifest: {len(texture_paths)} translated texture(s)')

    with zipfile.ZipFile(OUT_ZIP, 'w', zipfile.ZIP_DEFLATED) as zf:

        # --- Text translation files ---
        for fname in sorted(os.listdir(TEXT_DIR)):
            if not fname.endswith('.txt'):
                continue
            if fname in TEXT_SKIP or fname.endswith('.bak'):
                continue
            fpath = os.path.join(TEXT_DIR, fname)
            arc_path = f'BepInEx/Translation/en/Text/{fname}'
            zf.write(fpath, arc_path)
            print(f'  text      {arc_path}')

        # --- Translated textures only ---
        for rel in texture_paths:
            fpath = os.path.join(BASE, rel.replace('/', os.sep))
            if os.path.isfile(fpath):
                zf.write(fpath, rel)
                print(f'  texture   {rel}')
            else:
                print(f'  MISSING   {rel}')

        # --- BepInEx binaries and config ---
        bepinex_root = os.path.join(BASE, 'BepInEx')
        for folder in BEPINEX_INCLUDE:
            folder_path = os.path.join(bepinex_root, folder)
            if not os.path.isdir(folder_path):
                continue
            for dirpath, _, filenames in os.walk(folder_path):
                for fname in filenames:
                    fpath = os.path.join(dirpath, fname)
                    rel_path = os.path.relpath(fpath, BASE).replace('\\', '/')

                    # Patch config in-memory — don't modify the file on disk
                    if os.path.normpath(fpath) == os.path.normpath(CONFIG_FILE):
                        with open(fpath, 'r', encoding='utf-8') as f:
                            content = patch_config(f.read())
                        zf.writestr(rel_path, content)
                        print(f'  config    {rel_path} (EnableTextureDumping=False)')
                    else:
                        zf.write(fpath, rel_path)

        # --- Doorstop and other root files ---
        for fname in ROOT_FILES:
            fpath = os.path.join(BASE, fname)
            if os.path.isfile(fpath):
                zf.write(fpath, fname)
                print(f'  root      {fname}')
            else:
                print(f'  MISSING   {fname}')

    size_mb = os.path.getsize(OUT_ZIP) / 1_048_576
    print(f'\nWrote {OUT_ZIP} ({size_mb:.1f} MB)')


if __name__ == '__main__':
    build()
