"""
contribute.py — Chase Chase Jokers Translation Contribution Helper
==================================================================
Step 1 — stage new strings for review:
    py contribute.py
    py contribute.py path/to/_AutoGeneratedTranslations.txt

    Reads _AutoGeneratedTranslations.txt (game dump), finds strings not yet
    in the themed files, classifies them, and writes them to staging/<category>.txt
    for a maintainer to review in the pull request.

Step 2 — apply reviewed staging files to the real translation files:
    py contribute.py --apply

    Merges every file in staging/ into the matching file in
    BepInEx/Translation/en/Text/, then clears the staging folder.

Textures:
    Drop new .png files into BepInEx/Translation/en/Texture/ and run either
    command — they will be moved to the correct subfolder automatically.
"""

import os
import re
import sys
import json
import shutil

TEXT_DIR      = r'BepInEx/Translation/en/Text'
TEXTURE_DIR   = r'BepInEx/Translation/en/Texture'
STAGING_DIR   = r'staging'
MANIFEST_FILE = r'translated_textures.json'
DEFAULT_SRC   = r'_AutoGeneratedTranslations.txt'

# ---------------------------------------------------------------------------
# Classification (mirrors split_translations.py)
# ---------------------------------------------------------------------------

TITLE_COLOR = re.compile(
    r'<color\\=#(ff067c|ffde00|5fe7ff|ff4ba0|ff4bce|c0ff00|ff2c9a|ff1717|'
    r'e49bff|00ea90|00e3ff|ade0f1)>'
)

SYSTEM_KW = [
    'テストモード=', 'ゲーム設定=', 'ネットワーク設定=', 'ネットワークチェック=',
    'コイン設定=', 'ディスクチェック=', 'ＩＣカードチェック=', 'ICカードチェック=',
    'サウンド設定=', '言語設定=', 'システム情報=', 'DHCPサーバー=', 'NTPサーバー=',
    'MACアドレス=', 'DNSサーバー=', 'IPアドレス=', 'デフォルトルーター=',
    'サブネットマスク=', 'モニター解像度エラー=', 'サブモニター解像度エラー=',
    'キャリブレーション=', '暗証番号入力=', '確認入力=',
    'ｅ-ａｍｕｓｅｍｅｎｔ ｐａｓｓを確認', 'ＰＡＳＥＬＩ確認中',
    'ＰＡＳＥＬＩを使用', 'センターサーバー', 'すべて初期化=', '集計データ=',
    '時刻設定=', '電子マネー=', 'ゲームモード=', 'ゲームモード（デフォルト）=',
    'メインメニュー=', 'ランプチェック=', 'タッチパネルチェック=',
    'アナログスティックチェック=', 'トラックボールチェック=', '入力チェック=',
    '制御チェック=', '本体チェック=', '画面チェック=', 'カラーチェック=',
    'サービスボタン履歴=', '接続状態=', '保存して終了=', 'マッチングコード=',
    '限定マッチング中=', '営業終了時間=', '閉店設定=', 'サーバーとの通信=',
    'センターとの通信=', 'ルーターとの通信=', 'オンラインアップデートの準備',
    'SERVICEボタン \\= ', 'TESTボタン \\= ', 'テストボタン \\= ',
    'サービスボタン \\= ', 'OKボタン \\= ', '<color\\=cyan>OKボタン',
    '<color\\=cyan>上/下ボタン', '<color\\=cyan>左/右ボタン',
    '<color\\=cyan>左/下ボタン', 'プレーヤー名表示設定=',
    'このデータでゲームを始めます=', 'ｅ-ａｍｕｓｅｍｅｎｔサイト',
    '中心X座標', 'ＳＴＥＰ', '感知しない範囲:', '保存中=',
    'ネットワーク接続状況確認中', 'ルーターからインターネット', '日本語=',
    '完了しました=', 'カード認証=', 'あと1コイン=', 'クレジット=',
    'スティックを動かしてください=', 'クレジットでプレー=', 'ＰＡＳＥＬＩでプレー=',
    '円（税込）=', 'サーバー=server', 'センター=Center', 'ルーター=router',
    '本体=Main', '終了=Exit', '初期化=Defaults', 'チーム=team', '時刻=time',
    '保存中=Saving', '時刻設定未設定=', 'このゲーム機は チームＡ',
    'ジョーカーチェイスはじまるヨ', 'お知らせ準備中=', 'こちらに日付',
    'ランキング圏外=', 'チェイスチェイスジョーカーズに参戦=',
    '制作・著作 株式会社コナミ', '禁止行為', 'プレー状況をゲームサーバー',
    '限定マッチング=Limited', 'テストモード->時刻設定',
    '<color\\=cyan>左/右ボタン \\= 設定', 'TESTボタン \\= 設定',
    'SERVICEボタン \\= 設定', '未設定=Not set', 'あと１コイン=',
    'ネットワーク接続', 'カードナンバー',
    '<color\\=#F9FF00>確認</color>しました', '<color\\=#F9FF00>暗証番号</color>',
    'しばらくお待ちください=', '数字はランダムで表示', 'ランキング=Ranking',
    '<color\\=#dc3096>ｅ-ａｍｕｓｅｍｅｎｔサイト',
    'ゲーム中、<color', '※ご注意※', 'ＰＡＳＥＬＩ確認中',
    'このデータでゲームを', 'タッチパネルを押している間', '以下が正しく消費されずに',
]
TUTORIAL_KW = [
    '<alpha\\=#00>1<alpha\\=#FF>',
    'チュートリアルをプレーしてみよう=',
    '今日もめいっぱい働けヨ～♪=',
]
MUSIC_KW = [
    'チェイスチェイスジョーカーズのうた', 'カラフルミニッツ=', 'ＤＪ ＴＯＴＴＯ',
    '伐折羅-ｖａｊｒａ-=', '疾風=Hayate', 'ピアノ協奏曲第１番', '猫叉Ｍａｓｔｅｒ=',
    '紅色リトマス=', '凛として咲く花の如く=', '三代目 ＡＤＵＬＴＩＣ',
    'レッツゴー！ボンバーガール', '実況ガール=', 'アーティスト名=',
    'ラストワンＢＧＭリスト=', '設定中ラストワンＢＧＭ=', '曲名こちら=',
    '※タマシイが残り１つの時にかかるＢＧＭを変更',
    'カグラ=Kagura', 'ツカサ=Tsukasa', 'シーズ=Seeds', 'ベール=Veil',
    'ブラッド=Brad', 'スズ=Tin', 'サツキ=Satsuki', 'レフ=Reflex',
    'ゲンシン=Genshin', 'ホン=Phon', 'アザリン=Azarin', 'さな=Beyond',
    'カギコ&チノン（ＣＶ:',
]
CHARACTER_KW = [
    'ＣＶ:', 'CV:', 'の制服=', 'の靴=', 'の鬼装束=', 'の鬼靴=', 'の斧=',
    'の鎌=', 'のベレー帽=', 'のランドセル=', 'のメス=', 'の金棒=',
    'の鬼帽子=', 'の鉄球=', 'の裁ちばさみ=', 'の大包丁=', '５５寸釘=',
    'アルティメットマジカルポテトマッシャー', 'の制服（誕生日', 'のリボン（誕生日',
    'あかぎ=Akagi', 'あくあ=Aqua', 'くびづか=Kubitsuka', 'しなず=Shinazu',
    'かばらい=Kabarai', 'もあ=Moa', 'あとべ=Atobe', 'かがじょう=Hanagajou',
    'マラリヤ=Malariya', 'くれは=Kureha', '貞子=Sadako', 'さだこ=Sadako',
    'パイン=Pine', '花子=Hanako', 'はなこ=Hanako',
]
COSMETIC_KW = [
    'カチューシャ=', 'カチューシャ（', 'サンダル=', 'サンダル（', 'ブーツ=',
    'ブーツ（', 'シューズ=', 'シューズ（', 'パンプス=', 'パンプス（',
    'ローファー=', 'ローファー（', 'セーラー服=', 'セーラー服（', 'メイド服=',
    'メイド服（', 'ワンピ水着=', 'ワンピ水着（', 'ワンピ=', 'ワンピ（',
    'ドレス=', 'ドレス（', 'ビキニ=', 'ビキニ（', 'スイムウェア=', 'スイムウェア（',
    'スクール水着=', 'スクール水着（', '帽子=', '帽子（', 'ベレー帽=',
    'ゴーグル=', 'ゴーグル（', 'サングラス=', 'サングラス（', 'メガネ=',
    'メガネ（', 'マスク=', 'マスク（', 'お面=', 'お面（', 'エプロン=',
    'エプロン （', 'ジャケット=', 'ジャケット（', 'コスチューム=', 'コスチューム（',
    'コブン=', 'コブン（', 'ミミ=', 'ミミ（', 'リボン=', 'リボン（',
    '麦わら帽子=', '麦わら帽子（', 'カンザシ=', 'カンザシ（', 'タートルネック=',
    'シャツ=', 'シャツ（', 'ドレスアップ=Dress up', '装備無し=',
]
TITLE_KW = [
    'shogo_mark_', 'でプレー=Play in', 'トップ１０入り=', 'トップ１００入り=',
    'カギコのレベルが', 'チノンのレベルが', 'ボタンのレベルが', 'ツバキのレベルが',
    'ミヨミのレベルが', 'パインのレベルが', 'チアモのレベルが', 'クルルのレベルが',
    'ミロクのレベルが', 'ジョウカのレベルが', '紅刃のレベルが', 'マラリヤのレベルが',
    'ツバキ廻のレベルが', 'ツバキ【廻】のレベルが',
    '２０２２年', '２０２３年', '２０２４年', '２０２５年', '新人チェイサー=',
]
MISSION_KW = [
    'ミッション内容=', '練習をプレーしてみよう=', '全国対戦をプレーしてみよう=',
    'キャラクターを強化してみよう=', 'カスタマイズ編=', 'サブスキルを変更してみよう=',
    '称号を変えてみよう=', 'ドレスアップパーツを変えてみよう=',
    'デグチへの突入を成功させよう=', 'まずはここから=',
    'を１０回ヒットさせた=', 'を５０回ヒットさせた=', 'を１００回ヒットさせた=',
    'を２００回発動=', 'を１０００回発動=', 'を２０００回発動=',
    'を４００秒発動=', 'を８００秒発動=', 'を１０００秒発動=',
    'を１０回使用=', 'を５０回使用=', 'を１００回使用=',
    'を３０回獲得=', 'を２０回防いだ=', 'チェインを２００回', 'ＭＶＰを',
    'アシストＰを', 'ワープポイントを３０回使用=', 'ジャンプポイントを１００回使用=',
    'ドレスアップパーツを５０以上所持=', 'ドレスアップパーツを１００以上所持=',
    '帰還を３０回獲得=', '敵を１００回倒した=', '敵を３００回倒した=',
    'デグチへの突入を２０回防いだ=', 'チェインを２００回繋いだ=',
]


def classify(s):
    if not s or '=' not in s:
        return None
    for kw in SYSTEM_KW:
        if kw in s: return 'system'
    for kw in TUTORIAL_KW:
        if kw in s: return 'tutorial'
    for kw in MUSIC_KW:
        if kw in s: return 'music'
    for kw in CHARACTER_KW:
        if kw in s: return 'characters'
    if 'color\\=#dc3096>' in s: return 'skills'
    if 'color\\=#18bcf2>' in s: return 'abilities'
    for kw in TITLE_KW:
        if kw in s: return 'titles'
    if TITLE_COLOR.search(s): return 'titles'
    for kw in COSMETIC_KW:
        if kw in s: return 'cosmetics'
    for kw in MISSION_KW:
        if kw in s: return 'missions'
    return 'gameplay'


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def load_existing_keys(text_dir):
    keys = set()
    for fname in os.listdir(text_dir):
        if not fname.endswith('.txt') or fname.startswith('_'):
            continue
        with open(os.path.join(text_dir, fname), 'r', encoding='utf-8-sig') as f:
            for line in f:
                line = line.strip()
                if '=' in line:
                    keys.add(line.split('=', 1)[0])
    return keys


SCENE_FOLDERS = {
    'card_entry', 'character_setting', 'chat', 'common', 'gameover',
    'gameplay', 'matching', 'mode_select', 'result', 'sakasamatower',
    'shop', 'stage', 'tutorial',
}


def get_scene(fname):
    m = re.match(r'sactx-\d+-\d+x\d+-\w+-([a-z_]+)-', fname)
    if m:
        return m.group(1)
    if fname.startswith('matching_rank_'):
        return 'matching'
    if fname.startswith('ui_chat_') or fname.startswith('ui_emote'):
        return 'chat'
    if fname.startswith('ui_stage_name_'):
        return 'stage'
    if fname.startswith('body_') or fname.startswith('headacc_') or fname.startswith('shoes_') or fname.startswith('weapon_') or fname.startswith('other_'):
        return 'item_dressup'
    if fname.startswith('ui_consume') or fname.startswith('ui_dress'):
        return 'item_obtain'
    if fname.startswith('ui_information_'):
        return 'information'

    return None


def sort_loose_files(scan_dir, dest_prefix, texture_dir, moved):
    """Sort any loose .png/.psd files in scan_dir into dest_prefix/<scene>/ subfolders."""
    for fname in os.listdir(scan_dir):
        fpath = os.path.join(scan_dir, fname)
        if os.path.isdir(fpath):
            continue
        if not (fname.endswith('.png') or fname.endswith('.psd')):
            continue
        scene = get_scene(fname)
        if scene is None:
            if not (scan_dir.endswith('ignored') or scan_dir.endswith('need_sorting')):
                print(f'  [texture] WARNING: no scene rule for "{fname}" — left in place')
                continue
            continue
        dest_dir = os.path.join(texture_dir, dest_prefix, scene)
        os.makedirs(dest_dir, exist_ok=True)
        dest_path = os.path.join(dest_dir, fname)
        replacing = os.path.isfile(dest_path)
        if replacing:
            os.remove(dest_path)
        shutil.move(fpath, dest_path)
        action = 'replaced' if replacing else 'moved'
        moved.append((dest_prefix, scene, fname, action))


def find_in_untranslated(texture_dir, fname):
    """Return all paths under _untranslated/ that match fname."""
    untranslated_dir = os.path.join(texture_dir, '_untranslated')
    matches = []
    if not os.path.isdir(untranslated_dir):
        return matches
    for dirpath, _, files in os.walk(untranslated_dir):
        if fname in files:
            matches.append(os.path.join(dirpath, fname))
    return matches


def check_duplicates(texture_dir):
    """Warn about textures that appear in more than one location under Texture/."""
    seen = {}  # fname -> list of paths
    for dirpath, _, files in os.walk(texture_dir):
        for fname in files:
            if fname.endswith('.png') or fname.endswith('.psd'):
                seen.setdefault(fname, []).append(
                    os.path.relpath(os.path.join(dirpath, fname), texture_dir).replace('\\', '/')
                )
    duplicates = {f: paths for f, paths in seen.items() if len(paths) > 1}
    if duplicates:
        print(f'  WARNING: {len(duplicates)} duplicate filename(s) found:')
        for fname, paths in sorted(duplicates.items()):
            for p in paths:
                print(f'    {p}')
    return duplicates


def organise_textures(texture_dir, mark_translated=False, base=None):
    """Sort loose texture files into scene subfolders.

    - Texture/ root         -> Texture/<scene>/ (--translated)
                               Texture/_untranslated/<scene>/ (default)
    - _untranslated/ root   -> _untranslated/<scene>/
    - _untranslated/<cat>/  -> _untranslated/<cat>/<scene>/  (contributor-created folders)

    With --translated: removes any copies found under _untranslated/.
    Always checks for duplicate filenames across all subfolders.
    If mark_translated=True, .png paths are registered in translated_textures.json.
    """
    moved = []
    untranslated_dir = os.path.join(texture_dir, '_untranslated')

    # Sort files dropped in Texture/ root
    root_prefix = '' if mark_translated else '_untranslated'
    sort_loose_files(texture_dir, root_prefix, texture_dir, moved)

    # Sort files dropped in _untranslated/ root and any contributor subfolders within it
    if os.path.isdir(untranslated_dir):
        sort_loose_files(untranslated_dir, '_untranslated', texture_dir, moved)
        for entry in sorted(os.listdir(untranslated_dir)):
            entry_path = os.path.join(untranslated_dir, entry)
            if os.path.isdir(entry_path) and entry.lower() not in SCENE_FOLDERS:
                sort_loose_files(entry_path, os.path.join('_untranslated', entry), texture_dir, moved)

    # If translating: remove any copies of the same file from _untranslated/
    if mark_translated and moved:
        for _, _, fname, _ in moved:
            stale = find_in_untranslated(texture_dir, fname)
            for path in stale:
                os.remove(path)
                rel = os.path.relpath(path, texture_dir).replace('\\', '/')
                print(f'  removed from _untranslated/  {rel}')

    # Check for duplicates across all subfolders
    print('  Checking for duplicates...')
    dupes = check_duplicates(texture_dir)
    if not dupes:
        print('  No duplicates found.')

    if mark_translated and moved and base:
        manifest_path = os.path.join(base, MANIFEST_FILE)
        existing = []
        if os.path.isfile(manifest_path):
            with open(manifest_path, 'r', encoding='utf-8') as f:
                existing = json.load(f)
        existing_set = set(existing)
        new_entries = []
        for prefix, scene, fname, _replacing in moved:
            if fname.endswith('.png'):
                rel = f'{TEXTURE_DIR}/{prefix}/{scene}/{fname}'.replace('\\', '/').replace('//', '/')
                if rel not in existing_set:
                    new_entries.append(rel)
        if new_entries:
            updated = sorted(existing + new_entries)
            with open(manifest_path, 'w', encoding='utf-8') as f:
                json.dump(updated, f, indent=2, ensure_ascii=False)
                f.write('\n')
            print(f'  Added {len(new_entries)} texture(s) to {MANIFEST_FILE}')

    return [(f'{os.path.join(prefix, scene)}/{fname}', action) for prefix, scene, fname, action in moved]


# ---------------------------------------------------------------------------
# Stage command
# ---------------------------------------------------------------------------

def cmd_stage(base, src_file, mark_translated=False):
    text_dir    = os.path.join(base, TEXT_DIR)
    texture_dir = os.path.join(base, TEXTURE_DIR)
    staging_dir = os.path.join(base, STAGING_DIR)

    # Textures first
    print('=== Textures ===')
    moved = organise_textures(texture_dir, mark_translated=mark_translated, base=base)
    if moved:
        default_label = '[translated]' if mark_translated else '[untranslated]'
        for f, action in moved:
            label = f'[{action}]' if action == 'replaced' else default_label
            print(f'  {label}  {f}')
        print(f'  {len(moved)} file(s) organised.')
    else:
        print('  Nothing to organise.')

    # Strings
    print(f'\n=== Strings: {src_file} ===')
    if not os.path.isfile(src_file):
        print(f'ERROR: {src_file} not found.')
        sys.exit(1)

    existing_keys = load_existing_keys(text_dir)
    # Also include anything already in staging so re-runs don't duplicate
    if os.path.isdir(staging_dir):
        existing_keys |= load_existing_keys(staging_dir)

    print(f'  {len(existing_keys)} existing keys (translated + staged).')

    with open(src_file, 'r', encoding='utf-8-sig') as f:
        incoming = f.readlines()

    buckets      = {}
    skipped_dup  = 0
    skipped_bad  = 0

    for raw in incoming:
        line = raw.rstrip('\n\r')
        if not line or line.startswith('//') or line.startswith('#'):
            continue
        if '=' not in line:
            skipped_bad += 1
            continue
        jp_key = line.split('=', 1)[0]
        if jp_key in existing_keys:
            skipped_dup += 1
            continue
        cat = classify(line)
        buckets.setdefault(cat, []).append(raw if raw.endswith('\n') else raw + '\n')
        existing_keys.add(jp_key)

    if not buckets:
        print('  No new strings found.')
        return

    os.makedirs(staging_dir, exist_ok=True)
    added_total = 0
    for cat, lines in sorted(buckets.items()):
        dest_file = os.path.join(staging_dir, f'{cat}.txt')
        # Append to staging file (supports multiple runs)
        with open(dest_file, 'a', encoding='utf-8') as f:
            f.writelines(lines)
        print(f'  staged {len(lines):>4}  ->  staging/{cat}.txt')
        added_total += len(lines)

    print(f'\n  New strings staged : {added_total}')
    print(f'  Skipped (duplicate): {skipped_dup}')
    if skipped_bad:
        print(f'  Skipped (no "=")   : {skipped_bad}')
    print(f'\nReview staging/ then run:  py contribute.py --apply')


# ---------------------------------------------------------------------------
# Apply command
# ---------------------------------------------------------------------------

def cmd_apply(base):
    text_dir    = os.path.join(base, TEXT_DIR)
    staging_dir = os.path.join(base, STAGING_DIR)

    if not os.path.isdir(staging_dir) or not os.listdir(staging_dir):
        print('Nothing in staging/ to apply.')
        return

    print('=== Applying staging -> translation files ===')
    applied_total = 0
    for fname in sorted(os.listdir(staging_dir)):
        if not fname.endswith('.txt'):
            continue
        src  = os.path.join(staging_dir, fname)
        dest = os.path.join(text_dir, fname)
        with open(src, 'r', encoding='utf-8') as f:
            lines = f.readlines()
        with open(dest, 'a', encoding='utf-8') as f:
            f.writelines(lines)
        os.remove(src)
        print(f'  applied {len(lines):>4}  ->  {fname}')
        applied_total += len(lines)

    # Remove staging dir if empty
    if not os.listdir(staging_dir):
        os.rmdir(staging_dir)

    print(f'\n  Total applied: {applied_total}')
    print('  staging/ cleared.')


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    base = os.path.dirname(os.path.abspath(__file__))

    if '--apply' in sys.argv:
        cmd_apply(base)
        return

    mark_translated = '--translated' in sys.argv

    # Determine source file
    args = [a for a in sys.argv[1:] if not a.startswith('--')]
    if args:
        src_file = args[0]
    else:
        src_file = os.path.join(base, DEFAULT_SRC)

    cmd_stage(base, src_file, mark_translated=mark_translated)


if __name__ == '__main__':
    main()
